#!/usr/bin/env python3

import requests
from os import environ
import sys


if len(sys.argv) > 1:

    if sys.argv[1] == 'adicionar':
        data = {"texto":sys.argv[2], "mensagem":sys.argv[3]}

        r = requests.post(url = 'http://' + environ['IPADDR']+'/tarefa',  json=data)
        print(r.text)

    elif sys.argv[1] == 'listar':
        r = requests.get('http://' + environ['IPADDR']+'/tarefa')
        print(r.text)

    elif sys.argv[1] == 'buscar':
        r = requests.get('http://' + environ['IPADDR']+'/tarefa/'+sys.argv[2])
        print(r.text)

    elif sys.argv[1] == 'apagar':
        r = requests.delete('http://' + environ['IPADDR']+'/tarefa/'+sys.argv[2])
        print(r.text)

    elif sys.argv[1] == 'atualizar':
        data = {"titulo":sys.argv[3], "mensagem":sys.argv[4]}
        r = requests.put(url = 'http://' + environ['IPADDR']+'/tarefa/'+sys.argv[2],  json=data)
        print(r.text)

    elif sys.argv[1] == 'help':
        print("execute o seguinte commando no terminal:")
        print('PATH="caminho_ate_a_pasta_em_que_esta_seu_arquivo:$PATH\n')
        print("1 - Para \033[5;32;49madicionar\033[0;37;49m uma tarefa escreva \033[1;31;49m tarefa adicionar <titulo> <mensagem>\033[0;37;49m  no terminal\n")
        print("2 - Para \033[5;32;49mlistar\033[0;37;49m suas tarefas escreva \033[1;31;49m 'tarefa listar'\033[0;37;49m no terminal \n")
        print("3 - Para \033[5;32;49mbuscar\033[0;37;49m uma tarefa escreva \033[1;31;49m 'tarefa buscar id_tarefa'\033[0;37;49m no terminal \n")
        print("4 - Para \033[5;32;49mapagar\033[0;37;49m uma tarefa escreva \033[1;31;49m 'tarefa apagar id_tarefa'\033[0;37;49m no terminal \n")
        print("5 - Para \033[5;32;49matualizar\033[0;37;49m uma tarefa escreva \033[1;31;49m 'tarefa atualizar id_tarefa <titulo> <mensagem>'\033[0;37;49m no terminal\n")
        print("Se o seu título ou mensagem tiver mais de uma palavra coloque-o entre aspas")


    else:
        print("Erro: O programa não foi utilizado corretamente")
        print("digite \033[1;31;49m'tarefa help' \033[0;37;49mpara mais informações")
else:
        print("Erro: O programa não foi utilizado corretamente")
        print("digite \033[1;31;49m'tarefa help' \033[0;37;49mpara mais informações")